name: flickr_explore_count

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      start:
        description: 'start date'
        default: '2005-01-01'
        required: true
        type: string
      end:
        description: 'end date'
        default: '2005-01-01'
        required: true
        type: string


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: prepare pip package
      run: pip install requests
    - run: mkdir result.log
    - name: run
      run: python get_from_git.py ${{ inputs.start }} ${{ inputs.end }}
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: "result_${{ inputs.start }}__${{ inputs.s }}"
        path: result.log
